### ISSUE TITLE
Getting this error?

### ISSUE THREAD

**Issue by lakstick** [iirh/Howling-Software-V2#1]
The "Resources" element does not contain "Cheat" checks

**Comment by LoveyGoo** [comment]
same :/

**Comment by WhoSThereS** [comment]
put your hack aka dll in the resource.resx drop it in. it's in properties! 
then go to the error use the name that is used on your hack aka dll (don't do it with the extension!).

**Comment by LoveyGoo** [comment]
Where's the resources.resx tho in the solution or on the folders? And what so u mean for the error part can you please explain it by a step by step?

**Comment by WhoSThereS** [comment]
https://imgur.com/a/72C8FsG here it is located and btw can you help me idk how to register

**Comment by LoveyGoo** [comment]
Register on what?

**Comment by LoveyGoo** [comment]
Oh yeah sorry I'm high af

**Comment by LoveyGoo** [comment]
Use authed.io for it

**Comment by WhoSThereS** [comment]
So you make a licence?

**Comment by WhoSThereS** [comment]
and type the key in the key section?

**Comment by LoveyGoo** [comment]
There's a video about that on void.to let me find it for u

**Comment by WhoSThereS** [comment]
thx dude !

**Comment by LoveyGoo** [comment]
There's a tutorial when you reply on the thread 
https://void.to/Thread-Official-Release-Howling-Software-Loader-V2

**Comment by LoveyGoo** [comment]
So what did you mean drop the DLL in resources.resx and do y do what with extensions?

**Comment by WhoSThereS** [comment]
Ok you drop the dll in the resource.resx https://imgur.com/a/72C8FsG here it is located then you change the name of the $"hmodule =0x{injector.Inject(Howling_Software.Properties.Resources.changethis toyourdllname).ToInt64():x8}"; no extension like .dll just the name and then change this public static string CheatName = "yourdllname"; // Cheat name in resource.resx

**Comment by WhoSThereS** [comment]
i still don't know how to register

**Comment by LoveyGoo** [comment]
Gonna try that and see

**Comment by WhoSThereS** [comment]
i got it

**Comment by lakstick** [comment]
GO TO PW DONT SPAM ME IDIOT

**Comment by WhoSThereS** [comment]
ownage

**Comment by WhoSThereS** [comment]
Another problem is that the dll doesn't inject

**Comment by LoveyGoo** [comment]
same problem
