### ISSUE TITLE
Compile error (SOLVED)

### ISSUE THREAD

**Issue by Shaxzy** [iirh/Howling-Software-V2#2]
Sorry for not understanding, I'm probably just blind.

1>------ Build started: Project: Howling_Software, Configuration: Release Any CPU ------
1>E:\Visual Studio\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Authed". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
1>E:\Visual Studio\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "jose-jwt". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
1>C:\Users\Henning\Desktop\dll-master\Howling-Software-V2-master\Howling_Software\AdminPanel.cs(10,7,10,13): error CS0246: The type or namespace name 'Authed' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\Henning\Desktop\dll-master\Howling-Software-V2-master\Howling_Software\AdminPanel.cs(11,7,11,11): error CS0246: The type or namespace name 'Jose' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\Henning\Desktop\dll-master\Howling-Software-V2-master\Howling_Software\loader.cs(10,7,10,13): error CS0246: The type or namespace name 'Authed' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\Henning\Desktop\dll-master\Howling-Software-V2-master\Howling_Software\loader.cs(12,7,12,11): error CS0246: The type or namespace name 'Jose' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\Henning\Desktop\dll-master\Howling-Software-V2-master\Howling_Software\Main.cs(14,7,14,13): error CS0246: The type or namespace name 'Authed' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\Henning\Desktop\dll-master\Howling-Software-V2-master\Howling_Software\Main.cs(15,7,15,11): error CS0246: The type or namespace name 'Jose' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\Henning\Desktop\dll-master\Howling-Software-V2-master\Howling_Software\Register.cs(10,7,10,13): error CS0246: The type or namespace name 'Authed' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\Henning\Desktop\dll-master\Howling-Software-V2-master\Howling_Software\Register.cs(11,7,11,11): error CS0246: The type or namespace name 'Jose' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\Henning\Desktop\dll-master\Howling-Software-V2-master\Howling_Software\loader.cs(102,56,102,74): error CS0246: The type or namespace name 'OnUserInvalidEvent' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\Henning\Desktop\dll-master\Howling-Software-V2-master\Howling_Software\loader.cs(107,55,107,72): error CS0246: The type or namespace name 'OnUserBannedEvent' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\Henning\Desktop\dll-master\Howling-Software-V2-master\Howling_Software\loader.cs(24,23,24,27): error CS0246: The type or namespace name 'Auth' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\Henning\Desktop\dll-master\Howling-Software-V2-master\Howling_Software\AdminPanel.cs(31,9,31,13): error CS0246: The type or namespace name 'Auth' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\Henning\Desktop\dll-master\Howling-Software-V2-master\Howling_Software\Register.cs(25,9,25,13): error CS0246: The type or namespace name 'Auth' could not be found (are you missing a using directive or an assembly reference?)
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by Shaxzy** [comment]
Sorry I'm blind lol. Figured it out /Closed

**Comment by LilSpoat** [comment]
well im blind as fuck so how did u fixed it lol?

**Comment by fxip** [comment]
hey dude  how u fixed it i have a problem with this and i cannnot fix pls add my discord
Up#9659
